name: Debug

on: [workflow_dispatch]
jobs:
  debug:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '3.8', '3.9', 'pypy-3.7' ]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Check python version
        if: matrix.os == 'windows-latest'
        run: |
          python -V
          pip -V
          where python
      - name: Check python version
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -V
          pip -V
          which python
